# Generated by Django 3.2.14 on 2022-08-08 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocokm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('videoThumbnail', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('publishTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewCount', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('videoURL', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'videoInfo',
            },
        ),
        migrations.DeleteModel(
            name='locationInfo',
        ),
    ]
