# Generated by Django 3.2.14 on 2022-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocokm', '0002_auto_20220708_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationinfo',
            name='publishTime',
            field=models.TimeField(),
        ),
    ]
