# Generated by Django 3.2.14 on 2022-08-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocokm', '0002_auto_20220808_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeName', models.CharField(max_length=50)),
                ('placeID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('x', models.DecimalField(decimal_places=18, max_digits=24)),
                ('y', models.DecimalField(decimal_places=18, max_digits=24)),
                ('category', models.CharField(max_length=50)),
                ('placeURL', models.CharField(max_length=50)),
                ('placeThumbnail', models.CharField(max_length=50)),
                ('placeRating', models.FloatField()),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocokm.video')),
            ],
            options={
                'db_table': 'locationInfo',
            },
        ),
    ]
